version: "3.8"
services:
  drupal:
    image: drupal:9.5.0
    ports:
      - "8080:80"
    volumes:
      - drupal_modules:/var/www/html/modules
      - drupal_profiles:/var/www/html/profiles
      - drupal_themes:/var/www/html/themes
      - drupal_sites:/var/www/html/sites
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  drupal_modules:
  drupal_profiles:
  drupal_sites:
  drupal_themes: